'use client'


import { Inter } from "next/font/google";
import "./globals.css";
import {theme} from '../chakraTheme'
import { HouseProvider } from "../Contexts/HouseContext";


import { ChakraProvider } from '@chakra-ui/react'

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Truliv",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <HouseProvider> 
      <ChakraProvider theme={theme}>
        {children}
        </ChakraProvider>
      </HouseProvider>
      </body>
    </html>
  );
}
